# matplotlib test 
import matplotlib.pyplot as plt
plt.plot([1,2,3])
plt.ylabel ('test')
plt.show()

#problem 1 
#If we list all the natural numbers below 10 that are multiples of 3 or 5, we get and 3,5,6,9. 
# The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000 .
import numpy 
x = range(1000)
count = 0
for n in x: 
    if n % 3 == 0 or n % 5 == 0: 
         count += n
print(count) 

#problem 2 
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2 , the first 10 terms will be: 1,2,3,5,8,13,21,34,55,89... By considering the terms in the 
# Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

num = 4000000
num1 = 3 
count = 1 
while count <= num: 
    count = sum(num-1, num-2)
    num1 += count
print(num1)


    